CREATE TABLE portafolio (
    id SERIAL PRIMARY KEY,
    TICKER VARCHAR(50),
    PPC INT,
    PPV INT,
    CAPITAL_DESTINADO INT,
    PORCENTAJE_DEL_PORTAFOLIO FLOAT
);

INSERT INTO portafolio (TICKER, PPC, PPV, CAPITAL_DESTINADO, PORCENTAJE_DEL_PORTAFOLIO) VALUES ('BTC', 60000, 90000, 3000, 60);